### ISSUE TITLE
 how to generate the depth image of the corresponding RGB image?

### ISSUE THREAD

**Issue by LZL-CS** [kaichen-z/VMLoc#1]
Hi @kaichen-z, thanks for your awesome work. How did you generate the depth image from the point cloud of the corresponding RGB image? Could you share your code?

**Comment by kaichen-z** [comment]
Dear LZL-CS, the depth map could be generated by the projecting point cloud into the image frame with the help of extrinsic and intrinsic matrices. Specifically, the depth map of 7Scenes is provided in their original dataset. The depth map of Robotcar could be generated by using this file: https://github.com/kaichen-z/VMLoc/blob/main/robotcar/python/project_laser_into_camera.py

**Comment by LZL-CS** [comment]
Hi @kaichen-z, thanks for your quick reply. About the depth map of Robotcar, I have two questions:
(1) The Robotcar dataset has two kinds of Lidars, 2D-LMS and 3D-LDMRS. Which one did you use?
(2) Indeed, the depth map of Robotcar could be generated by the Python function: **_project_laser_into_camera.py_**, but during the use of this function, we need to call https://github.com/kaichen-z/VMLoc/blob/main/robotcar/python/interpolate_poses.py, where we need to use relative pose or absolute pose?
![image](https://github.com/kaichen-z/VMLoc/assets/54640259/de9a367f-b584-46a1-8e04-c7c1ee514a84)

**Comment by kaichen-z** [comment]
Hello @LZL-CS,

To avoid any misunderstandings, please refer to the README file in their source code for the specific instructions on "Projecting point clouds into images." You can find the README at this link: https://github.com/samarth-robo/robotcar-dataset-sdk/tree/master/python. Additionally, it is important to note that we should utilize world coordinates when projecting the point cloud to depth.

Thank you.

**Comment by LZL-CS** [comment]
> Hello @LZL-CS,
> 
> To avoid any misunderstandings, please refer to the README file in their source code for the specific instructions on "Projecting point clouds into images." You can find the README at this link: https://github.com/samarth-robo/robotcar-dataset-sdk/tree/master/python. Additionally, it is important to note that we should utilize world coordinates when projecting the point cloud to depth.
> 
> Thank you.

Hi @kaichen-z, thank you very much for your reply. May I know what you mean about **it is important to note that we should utilize world coordinates when projecting the point cloud to depth.**?

Another question is, what is the time span setting  (default is 2e7) to get the point cloud?
https://github.com/kaichen-z/VMLoc/blob/0e4dde6c5144fe4613f0e101e622fa7d5b9fb78a/robotcar/python/build_pointcloud.py#L126C32-L126C32

**Comment by kaichen-z** [comment]
Hello @LZL-CS, I just want to bring to your attention the importance of using world coordinates instead of using relevant pose information. I use the default setting from (https://github.com/samarth-robo/robotcar-dataset-sdk/tree/master/python). Please refer to their source code for further information.

**Comment by LZL-CS** [comment]
> Hello @LZL-CS, I just want to bring to your attention the importance of using world coordinates instead of using relevant pose information. I use the default setting from (https://github.com/samarth-robo/robotcar-dataset-sdk/tree/master/python). Please refer to their source code for further information.

Hi @kaichen-z, thanks for your reply and reminder. I'm now closing this issue!
