### ISSUE TITLE
Question about data processing

### ISSUE THREAD

**Issue by LZL-CS** [kaichen-z/VMLoc#2]
Hi @kaichen-z, 
When you generate the image's corresponding depth image, do you use the _**ins.csv**_  pose file or _**vo.csv**_ pose file? Because the generated pointcloud values(x, y, z) are quite different when you choose different files.  When choosing the _**ins.csv**_  pose file, we get the pointcloud values(x, y, z) is relative coordinates. While choosing the _**vo.csv**_ pose file,  we get the pointcloud values(x, y, z) is absolute coordinates.

I appreciate any help you can provide!

https://github.com/samarth-robo/robotcar-dataset-sdk/blob/86b251284b5583182bcd9584952d5421cdfb0040/python/project_laser_into_camera.py#L29C24-L29C34

![image](https://github.com/kaichen-z/VMLoc/assets/54640259/d6b3b5e7-dc6d-45da-9314-868408ac05da)

**Comment by kaichen-z** [comment]
Hi, @LZL-CS. Use vo.csv, please.

**Comment by LZL-CS** [comment]
> Hi, @LZL-CS. Use vo.csv, please.

OK, thanks for your quick reply!
