### ISSUE TITLE
error when generate depth image

### ISSUE THREAD

**Issue by LZL-CS** [kaichen-z/VMLoc#3]
Hi @kaichen-z, when I tried to call` def interpolate_poses(pose_timestamps, abs_poses, requested_timestamps, origin_timestamp)`: https://github.com/kaichen-z/VMLoc/blob/3866bbc2abeb0653678fb11ba9d56f191bee113b/robotcar/python/interpolate_poses.py#L133

I got the error due to the `1 + R_zz - R_yy - R_xx <0` as below: 
https://github.com/kaichen-z/VMLoc/blob/3866bbc2abeb0653678fb11ba9d56f191bee113b/robotcar/python/transform.py#L138
<img width="1322" alt="image" src="https://github.com/kaichen-z/VMLoc/assets/54640259/2fbf54d1-85d8-4094-8f7a-0778890d0c1d">

<img width="1092" alt="image" src="https://github.com/kaichen-z/VMLoc/assets/54640259/c92fa47d-5f23-4232-8ef6-39b62ad32243">

Have you ever encountered this issue?

**Comment by kaichen-z** [comment]
@LZL-CS, I apologize, but I haven't encountered that issue. Perhaps you could consider reporting this error to the source repository.

**Comment by LZL-CS** [comment]
Hi @kaichen-z, thanks for your reply, I'll send the email to the author.
